

services:
  postgres:
    image: postgres:15
    container_name: travel_guide_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aliahsan
      POSTGRES_DB: travel_guide_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/utils/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: